### ISSUE TITLE
[META] Editor

### ISSUE THREAD

**Issue by wiomoc** [wiomoc/simulator#2]
Als Benutzer will ich in einem Editor eine eigene Karte anlegen können, welche ich 1. speichern und 2. spielen kann.

AC:
* [x] Seperater Frame
* [x] open/save from/to csv
* [x] upload map to server
* Validierung
  1. [ ] Ein kontinuierlicher Track
  2. [ ] Keine Überschneidungen
  3. [ ] Startziel
